[tool.poetry]
name = "sd-ocr-event"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"


[tool.poetry.scripts]
sd-ocr-event = "sd_ocr_event:main"
    
[tool.poetry.dependencies]
python = ">=3.11,<3.15"
typing_extensions = "4.15.0"
charset-normalizer = "3.4.7"
openvino = { version = "2025.4.1", extras = ["onnx"] }
openvino-telemetry = "2025.2.0"
numpy = "1.26.4"
pyopencl = "2026.1.2"
pyinstaller = "6.18.0"
pillow = "10.2.0"
rapidocr = "3.6.0"
onnxruntime = "1.19.2"
opencv-python-headless = "4.9.0.80"
Shapely = "1.8.5.post1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"